name: pos_v2
description: Offline POS v2 — Flutter + SQLite + GitHub Actions
publish_to: 'none'
version: 1.0.5+6

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  sqflite: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1
  blue_thermal_printer: ^1.2.3
  flutter_blue_plus: ^1.35.5
  shared_preferences: ^2.3.3
  image_picker: ^1.1.2
  image: ^3.3.0
  esc_pos_utils: ^1.1.0
  crypto: ^3.0.6
  package_info_plus: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
